site_name: Project Bees Knees

plugins:      
  - mermaid2
  - search
  - pdf-export:
      media_type: print
      combined: false 

docs_dir: docs/

theme:
  name: material
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  features:
    - instant

  font:
    text: PT Sans
    code: Fira Mono

extra_css:
  - css/style.css

extra_javascript:
  - https://unpkg.com/mermaid@8.14.0/dist/mermaid.min.js
